import { FONT_AMORIA, FONT_QRADA } from "@/lib/font";
import { Montserrat } from "next/font/google";
import Nav from "@/components/ui/nav";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Beyond Scences",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          FONT_QRADA.variable,
          FONT_AMORIA.variable,
          `${montserrat.variable} `
        )}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
